In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (from ucimlrepo) (3.0.4)
Requirement already satisfied: certifi>=2020.12.5 in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (from ucimlrepo) (2026.6.17)
Requirement already satisfied: numpy>=1.26.0 in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/magic_m/Schreibtisch/1_informatik/1_01_studium/26_SS/Data-Project-ML/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
regensburg_pediatric_appendicitis = fetch_ucirepo(id=938) 
  
# data (as pandas dataframes)
X = regensburg_pediatric_appendicitis.data.features 
y = regensburg_pediatric_appendicitis.data.targets 
  
# metadata 
print(regensburg_pediatric_appendicitis.metadata) 
  
# variable information 
print(regensburg_pediatric_appendicitis.variables)

{'uci_id': 938, 'name': 'Regensburg Pediatric Appendicitis', 'repository_url': 'https://archive.ics.uci.edu/dataset/938/regensburg+pediatric+appendicitis', 'data_url': 'https://archive.ics.uci.edu/static/public/938/data.csv', 'abstract': 'This repository holds the data from a cohort of pediatric patients with suspected appendicitis admitted with abdominal pain to Children’s Hospital St. Hedwig in Regensburg, Germany, between 2016 and 2021. Each patient has (potentially multiple) ultrasound (US) images, aka views, tabular data comprising laboratory, physical examination, scoring results and ultrasonographic findings extracted manually by the experts, and three target variables, namely, diagnosis, management and severity.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Image'], 'num_instances': 782, 'num_features': 53, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': ['Age', 'Sex'], 'target_col': ['Management', 'Severity', 'Diagnosis'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2023, 'last_updated': 'Tue Feb 06 2024', 'dataset_doi': '10.5281/zenodo.7669442', 'creators': ['Ricards Marcinkevics', 'Patricia Reis', 'Ugne Klimiene', 'Ece Ozkan', 'Kieran Chin-Cheong', 'Alyssia Paschke', 'Julia Zerres', 'Markus Denzinger', 'David Niederberger', 'S. Wellmann', 'C. Knorr', 'Julia E.'], 'intro_paper': {'ID': 354, 'type': 'NATIVE', 'title': 'Interpretable and Intervenable Ultrasonography-based Machine Learning Models for Pediatric Appendicitis', 'authors': 'Ricards Marcinkevics, Patricia Reis Wolfertstetter, Ugne Klimiene, Ece Ozkan, Kieran Chin-Cheong, Alyssia Paschke, Julia Zerres, Markus Denzinger, David Niederberger, S. Wellmann, C. Knorr, Julia E. Vogt', 'venue': 'Medical Image Analysis', 'year': 2023, 'journal': None, 'DOI': None, 'URL': 'https://arxiv.org/abs/2302.14460v2', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This dataset was acquired in a retrospective study from a cohort of pediatric patients admitted with abdominal pain to Children’s Hospital St. Hedwig in Regensburg, Germany. Multiple abdominal B-mode ultrasound images were acquired for most patients, with the number of views varying from 1 to 15. The images depict various regions of interest, such as the abdomen’s right lower quadrant, appendix, intestines, lymph nodes and reproductive organs. Alongside multiple US images for each subject, the dataset includes information encompassing laboratory tests, physical examination results, clinical scores, such as Alvarado and pediatric appendicitis scores, and expert-produced ultrasonographic findings. Lastly, the subjects were labeled w.r.t. three target variables: diagnosis (appendicitis vs. no appendicitis), management (surgical vs. conservative) and severity (complicated vs. uncomplicated or no appendicitis). The study was approved by the Ethics Committee of the University of Regensburg (no. 18-1063-101, 18-1063_1-101 and 18-1063_2-101) and was performed following applicable guidelines and regulations.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}, 'external_url': 'https://zenodo.org/records/7669442'}
                                name     role         type demographic  \
0                                Age  Feature   Continuous         Age
1                                BMI  Feature   Continuous         NaN
2                                Sex  Feature  Categorical         Sex
3                             Height  Feature   Continuous         NaN
4                             Weight  Feature      Integer         NaN
5                     Length_of_Stay  Feature      Integer         NaN
6                         Management   Target  Categorical         NaN
7                           Severity   Target  Categorical         NaN
8              Diagnosis_Presumptive    Other       Binary         NaN
9                          Diagnosis   Target       Binary         NaN
10                    Alvarado_Score  Feature      Integer         NaN
11     Paedriatic_Appendicitis_Score  Feature      Integer         NaN
12                    Appendix_on_US  Feature       Binary         NaN
13                 Appendix_Diameter  Feature      Integer         NaN
14                    Migratory_Pain  Feature       Binary         NaN
15              Lower_Right_Abd_Pain  Feature       Binary         NaN
16  Contralateral_Rebound_Tenderness  Feature       Binary         NaN
17                     Coughing_Pain  Feature       Binary         NaN
18                            Nausea  Feature       Binary         NaN
19                  Loss_of_Appetite  Feature       Binary         NaN
20                  Body_Temperature  Feature   Continuous         NaN
21                         WBC_Count  Feature   Continuous         NaN
22             Neutrophil_Percentage  Feature      Integer         NaN
23             Segmented_Neutrophils  Feature      Integer         NaN
24                      Neutrophilia  Feature  Categorical         NaN
25                         RBC_Count  Feature   Continuous         NaN
26                        Hemoglobin  Feature   Continuous         NaN
27                               RDW  Feature   Continuous         NaN
28                 Thrombocyte_Count  Feature      Integer         NaN
29                  Ketones_in_Urine  Feature  Categorical         NaN
30                      RBC_in_Urine  Feature  Categorical         NaN
31                      WBC_in_Urine  Feature  Categorical         NaN
32                               CRP  Feature      Integer         NaN
33                           Dysuria  Feature       Binary         NaN
34                             Stool  Feature  Categorical         NaN
35                       Peritonitis  Feature  Categorical         NaN
36                        Psoas_Sign  Feature  Categorical         NaN
37    Ipsilateral_Rebound_Tenderness  Feature  Categorical         NaN
38                      US_Performed  Feature  Categorical         NaN
39                         US_Number    Other      Integer         NaN
40                       Free_Fluids  Feature  Categorical         NaN
41              Appendix_Wall_Layers  Feature  Categorical         NaN
42                       Target_Sign  Feature  Categorical         NaN
43                     Appendicolith  Feature  Categorical         NaN
44                         Perfusion  Feature  Categorical         NaN
45                       Perforation  Feature  Categorical         NaN
46       Surrounding_Tissue_Reaction  Feature  Categorical         NaN
47              Appendicular_Abscess  Feature  Categorical         NaN
48                  Abscess_Location  Feature  Categorical         NaN
49          Pathological_Lymph_Nodes  Feature       Binary         NaN
50              Lymph_Nodes_Location  Feature  Categorical         NaN
51             Bowel_Wall_Thickening  Feature       Binary         NaN
52       Conglomerate_of_Bowel_Loops  Feature       Binary         NaN
53                             Ileus  Feature  Categorical         NaN
54                       Coprostasis  Feature  Categorical         NaN
55                         Meteorism  Feature  Categorical         NaN
56                         Enteritis  Feature  Categorical         NaN
57            Gynecological_Findings  Feature  Categorical         NaN

                                          description  units missing_values
0                     Obtained from the date of birth  years            yes
1   Measures body fat; patient's weight divided by...    NaN            yes
2                                   Registered gender    NaN            yes
3                                    Patient's height    NaN            yes
4                                    Patient's weight    NaN            yes
5                  Length of the stay in the hospital    NaN            yes
6   (conservative, primary surgical, secondary sur...    NaN            yes
7   (uncomplicated, complicated) Severity of appen...    NaN            yes
8                       Patient's suspected diagnosis    NaN            yes
9   Patient's diagnosis, histologically confirmed ...    NaN            yes
10    Patient's score according to the scoring system    NaN            yes
11    Patient's score according to the scoring system    NaN            yes
12  Detectability of the vermiform appendix during...    NaN            yes
13             Maximal outer diameter of the appendix    NaN            yes
14  Abdominal pain; usually starts in epigastrium ...    NaN            yes
15       Right iliac fossa pain detected on palpation    NaN            yes
16  A state in which pain of the contralateral sid...    NaN            yes
17                     Abdominal pain by forced cough    NaN            yes
18  Feeling of sickness/ejection of contents from ...    NaN            yes
19                                                NaN    NaN            yes
20  Measured by a thermometer placed in the rectum...    NaN            yes
21  The number of leucocytes in a unit volume of b...    NaN            yes
22              Mature WBC in the granulocytic series    NaN            yes
23  Most mature neutrophilic granulocytes present ...    NaN            yes
24  Relative neutrophilic leucocytosis, often a re...    NaN            yes
25  The number of erythrocytes in a unit volume of...    NaN            yes
26  Hemoglobin level; a red protein in the red blo...    NaN            yes
27  A blood test that measures the differences in ...    NaN            yes
28  The number of platelets in a unit volume of blood    NaN            yes
29  Presence of ketone bodies in urine, e.g. in ca...    NaN            yes
30                                     Blood in urine    NaN            yes
31    Leucocytes in urine, e.g., in case of infection    NaN            yes
32  Protein produced by the liver, elevated in cas...    NaN            yes
33          Pain or other difficulty during urination    NaN            yes
34                 Characteristics of bowel movements    NaN            yes
35  Spasm of abdominal wall muscles detected on pa...    NaN            yes
36    Abdominal pain produced by extension of the hip    NaN            yes
37  A state in which pain of the ipsilateral side ...    NaN            yes
38  If an abdominal ultrasonography was performed ...    NaN            yes
39                                                NaN    NaN            yes
40                     Free fluids inside the abdomen    NaN            yes
41  Distribution and characteristics of appendix l...    NaN            yes
42  Axial image of appendix with a fluid-filled ce...    NaN            yes
43  Presence of fecalith in the appendix, e.g. aco...    NaN            yes
44                    Blood flow to the appendix wall    NaN            yes
45                Signs of appendix perforation in US    NaN            yes
46  Inflammation signs in tissue (i.a. in omentum/...    NaN            yes
47                                   Appendiceal mass    NaN            yes
48             Location of the abcess intraperitoneal    NaN            yes
49  Enlarged and inflamed intra-abdominal lymph nodes    NaN            yes
50  The location of pathological lymph nodes in th...    NaN            yes
51  Edema of the intestinal wall, > 2-3 mm for sma...    NaN            yes
52  Small intestine conglomerate as sign of intrap...    NaN            yes
53  Sonographic signs of paralytic ileus (e.g., di...    NaN            yes
54                       Fecal impaction in the colon    NaN            yes
55               Accumulation of gas in the intestine    NaN            yes
56  Sonographic features of gastroenteritis, e.g. ...    NaN            yes
57  Gynaecological abnormalities, e.g. cysts, ovar...    NaN            yes

In [3]:
X.shape # (n_rows, n_cols)

(782, 53)

In [4]:
# Check the raw data immediately after loading, before any processing
print(X.isna().sum())

Age                                   1
BMI                                  27
Sex                                   2
Height                               26
Weight                                3
Length_of_Stay                        4
Alvarado_Score                       52
Paedriatic_Appendicitis_Score        52
Appendix_on_US                        5
Appendix_Diameter                   284
Migratory_Pain                        9
Lower_Right_Abd_Pain                  8
Contralateral_Rebound_Tenderness     15
Coughing_Pain                        16
Nausea                                8
Loss_of_Appetite                     10
Body_Temperature                      7
WBC_Count                             6
Neutrophil_Percentage               103
Segmented_Neutrophils               728
Neutrophilia                         50
RBC_Count                            18
Hemoglobin                           18
RDW                                  26
Thrombocyte_Count                    18
Ketones_in_Urine                    200
RBC_in_Urine                        206
WBC_in_Urine                        199
CRP                                  11
Dysuria                              29
Stool                                17
Peritonitis                           9
Psoas_Sign                           37
Ipsilateral_Rebound_Tenderness      163
US_Performed                          4
Free_Fluids                          63
Appendix_Wall_Layers                564
Target_Sign                         644
Appendicolith                       713
Perfusion                           719
Perforation                         701
Surrounding_Tissue_Reaction         530
Appendicular_Abscess                697
Abscess_Location                    769
Pathological_Lymph_Nodes            579
Lymph_Nodes_Location                661
Bowel_Wall_Thickening               683
Conglomerate_of_Bowel_Loops         739
Ileus                               722
Coprostasis                         711
Meteorism                           642
Enteritis                           716
Gynecological_Findings              756
dtype: int64

In [5]:
X.dtypes # dtype per column

Age                                 float64
BMI                                 float64
Sex                                     str
Height                              float64
Weight                              float64
Length_of_Stay                      float64
Alvarado_Score                      float64
Paedriatic_Appendicitis_Score       float64
Appendix_on_US                          str
Appendix_Diameter                   float64
Migratory_Pain                          str
Lower_Right_Abd_Pain                    str
Contralateral_Rebound_Tenderness        str
Coughing_Pain                           str
Nausea                                  str
Loss_of_Appetite                        str
Body_Temperature                    float64
WBC_Count                           float64
Neutrophil_Percentage               float64
Segmented_Neutrophils               float64
Neutrophilia                            str
RBC_Count                           float64
Hemoglobin                          float64
RDW                                 float64
Thrombocyte_Count                   float64
Ketones_in_Urine                        str
RBC_in_Urine                            str
WBC_in_Urine                            str
CRP                                 float64
Dysuria                                 str
Stool                                   str
Peritonitis                             str
Psoas_Sign                              str
Ipsilateral_Rebound_Tenderness          str
US_Performed                            str
Free_Fluids                             str
Appendix_Wall_Layers                    str
Target_Sign                             str
Appendicolith                           str
Perfusion                               str
Perforation                             str
Surrounding_Tissue_Reaction             str
Appendicular_Abscess                    str
Abscess_Location                        str
Pathological_Lymph_Nodes                str
Lymph_Nodes_Location                    str
Bowel_Wall_Thickening                   str
Conglomerate_of_Bowel_Loops             str
Ileus                                   str
Coprostasis                             str
Meteorism                               str
Enteritis                               str
Gynecological_Findings                  str
dtype: object

In [6]:
X.head() # first 5 rows

,Age,BMI,Sex,Height,Weight,Length_of_Stay,Alvarado_Score,Paedriatic_Appendicitis_Score,Appendix_on_US,Appendix_Diameter,...,Abscess_Location,Pathological_Lymph_Nodes,Lymph_Nodes_Location,Bowel_Wall_Thickening,Conglomerate_of_Bowel_Loops,Ileus,Coprostasis,Meteorism,Enteritis,Gynecological_Findings
0,12.68,16.9,female,148.0,37.0,3.0,4.0,3.0,yes,7.1,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14.10,31.9,male,147.0,69.5,2.0,5.0,4.0,no,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
2,14.14,23.3,female,163.0,62.0,4.0,5.0,3.0,no,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN
3,16.37,20.6,female,165.0,56.0,3.0,7.0,6.0,no,NaN,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,yes,NaN
4,11.08,16.9,female,163.0,45.0,3.0,5.0,6.0,yes,7.0,...,NaN,yes,reUB,NaN,NaN,NaN,NaN,NaN,yes,NaN

In [7]:
X.describe() # summary statistics for numerical columns

,Age,BMI,Height,Weight,Length_of_Stay,Alvarado_Score,Paedriatic_Appendicitis_Score,Appendix_Diameter,Body_Temperature,WBC_Count,Neutrophil_Percentage,Segmented_Neutrophils,RBC_Count,Hemoglobin,RDW,Thrombocyte_Count,CRP
count,781.000000,755.000000,756.000000,779.000000,778.000000,730.000000,730.000000,498.000000,775.000000,776.000000,679.000000,54.000000,764.000000,764.000000,756.000000,764.000000,771.000000
mean,11.346451,18.907012,148.017460,43.172542,4.284062,5.921918,5.253425,7.762651,37.404516,12.670683,71.791163,64.929630,4.799490,13.380497,13.180291,285.252618,31.386900
std,3.529909,4.385331,19.732016,17.390984,2.574057,2.155972,1.958456,2.536671,0.903678,5.366525,14.463656,15.085025,0.499012,1.393271,4.538774,72.494373,57.433854
min,0.000000,7.830000,53.000000,3.960000,1.000000,0.000000,0.000000,2.700000,26.900000,2.600000,27.200000,32.000000,3.620000,8.200000,11.200000,91.000000,0.000000
25%,9.200000,15.725000,137.000000,29.500000,3.000000,4.000000,4.000000,6.000000,36.800000,8.200000,61.400000,54.500000,4.537500,12.600000,12.300000,236.000000,1.000000
50%,11.440000,18.060000,149.650000,41.400000,3.000000,6.000000,5.000000,7.500000,37.200000,12.000000,75.500000,64.500000,4.780000,13.300000,12.700000,276.000000,7.000000
75%,14.100000,21.180000,163.000000,54.000000,5.000000,8.000000,7.000000,9.100000,37.900000,16.200000,83.600000,77.500000,5.020000,14.000000,13.300000,330.000000,33.000000
max,18.360000,38.160000,192.000000,103.000000,28.000000,10.000000,10.000000,17.000000,40.200000,37.700000,97.700000,91.000000,14.000000,36.000000,86.900000,708.000000,365.000000

In [8]:
import pandas as pd
nan_summary = pd.DataFrame({
    'dtype': X.dtypes,
    'non_null': X.notna().sum(),
    'nan_count': X.isna().sum(),
    'nan_pct': (X.isna().sum() / len(X) * 100).round(2)
})
nan_summary

                                    dtype  non_null  nan_count  nan_pct
Age                               float64       781          1     0.13
BMI                               float64       755         27     3.45
Sex                                   str       780          2     0.26
Height                            float64       756         26     3.32
Weight                            float64       779          3     0.38
Length_of_Stay                    float64       778          4     0.51
Alvarado_Score                    float64       730         52     6.65
Paedriatic_Appendicitis_Score     float64       730         52     6.65
Appendix_on_US                        str       777          5     0.64
Appendix_Diameter                 float64       498        284    36.32
Migratory_Pain                        str       773          9     1.15
Lower_Right_Abd_Pain                  str       774          8     1.02
Contralateral_Rebound_Tenderness      str       767         15     1.92
Coughing_Pain                         str       766         16     2.05
Nausea                                str       774          8     1.02
Loss_of_Appetite                      str       772         10     1.28
Body_Temperature                  float64       775          7     0.90
WBC_Count                         float64       776          6     0.77
Neutrophil_Percentage             float64       679        103    13.17
Segmented_Neutrophils             float64        54        728    93.09
Neutrophilia                          str       732         50     6.39
RBC_Count                         float64       764         18     2.30
Hemoglobin                        float64       764         18     2.30
RDW                               float64       756         26     3.32
Thrombocyte_Count                 float64       764         18     2.30
Ketones_in_Urine                      str       582        200    25.58
RBC_in_Urine                          str       576        206    26.34
WBC_in_Urine                          str       583        199    25.45
CRP                               float64       771         11     1.41
Dysuria                               str       753         29     3.71
Stool                                 str       765         17     2.17
Peritonitis                           str       773          9     1.15
Psoas_Sign                            str       745         37     4.73
Ipsilateral_Rebound_Tenderness        str       619        163    20.84
US_Performed                          str       778          4     0.51
Free_Fluids                           str       719         63     8.06
Appendix_Wall_Layers                  str       218        564    72.12
Target_Sign                           str       138        644    82.35
Appendicolith                         str        69        713    91.18
Perfusion                             str        63        719    91.94
Perforation                           str        81        701    89.64
Surrounding_Tissue_Reaction           str       252        530    67.77
Appendicular_Abscess                  str        85        697    89.13
Abscess_Location                      str        13        769    98.34
Pathological_Lymph_Nodes              str       203        579    74.04
Lymph_Nodes_Location                  str       121        661    84.53
Bowel_Wall_Thickening                 str        99        683    87.34
Conglomerate_of_Bowel_Loops           str        43        739    94.50
Ileus                                 str        60        722    92.33
Coprostasis                           str        71        711    90.92
Meteorism                             str       140        642    82.10
Enteritis                             str        66        716    91.56
Gynecological_Findings                str        26        756    96.68

In [9]:
col = 'Gynecological_Findings'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.583554
no appendicitis    0.416446
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.884615
no appendicitis    0.115385
Name: proportion, dtype: float64

In [10]:
y.head()

     Management       Severity        Diagnosis
0  conservative  uncomplicated     appendicitis
1  conservative  uncomplicated  no appendicitis
2  conservative  uncomplicated  no appendicitis
3  conservative  uncomplicated  no appendicitis
4  conservative  uncomplicated     appendicitis

In [11]:
y.describe()

          Management       Severity     Diagnosis
count            781            781           780
unique             4              2             2
top     conservative  uncomplicated  appendicitis
freq             483            662           463

In [12]:
X['Gynecological_Findings'].dropna()

14                                          Ovarialzyste
27                                          Zyste Uterus
158                                        Ovarialzyste
226                                         Ovarialzyste
260                                         Ovarialzyste
310                                         Ovarialzyste
495    In beiden Ovarien Zysten darstellbar, links Ov...
499              Ausschluss pathologischer Ovarialbefund
530                              kleine Ovarzyste rechts
532    kein Anhalt für eine gynäkologische Ursache de...
550                                 V. a. Ovarialtorsion
566              Ausschluss gyn. Ursache der Beschwerden
688                                                   ja
696                                                keine
723                                                keine
733                                                keine
734                                        Ovarialzysten
735                                                keine
736                                                keine
737                                                keine
738                                                keine
739                                                keine
743                                                keine
756                                     Ovarialzyste re.
776                                        Ovarialzysten
779                                          unauffällig
Name: Gynecological_Findings, dtype: str

In [13]:
# use median imputation for all columns with few missing values and numerical data:
X['Age'] = X['Age'].fillna(X['Age'].median())
X['BMI'] = X['BMI'].fillna(X['BMI'].median())
X['Height'] = X['Height'].fillna(X['Height'].median())
X['Weight'] = X['Weight'].fillna(X['Weight'].median())
X['Length_of_Stay'] = X['Length_of_Stay'].fillna(X['Length_of_Stay'].median())
X['Alvarado_Score'] = X['Alvarado_Score'].fillna(X['Alvarado_Score'].median())
X['Paedriatic_Appendicitis_Score'] = X['Paedriatic_Appendicitis_Score'].fillna(X['Paedriatic_Appendicitis_Score'].median())
X['Body_Temperature'] = X['Body_Temperature'].fillna(X['Body_Temperature'].median())
X['WBC_Count'] = X['WBC_Count'].fillna(X['WBC_Count'].median())
X['Neutrophil_Percentage'] = X['Neutrophil_Percentage'].fillna(X['Neutrophil_Percentage'].median())
X['RBC_Count'] = X['RBC_Count'].fillna(X['RBC_Count'].median())
X['Hemoglobin'] = X['Hemoglobin'].fillna(X['Hemoglobin'].median())
X['RDW'] = X['RDW'].fillna(X['RDW'].median())
X['Thrombocyte_Count'] = X['Thrombocyte_Count'].fillna(X['Thrombocyte_Count'].median())
X['CRP'] = X['CRP'].fillna(X['CRP'].median())

In [14]:
# For this variable, since there are only 2 missing values, we can drop the rows with missing values
# Get the indices of the 2 missing patients
drop_idx = X[X['Sex'].isna()].index

# Drop from both
X = X.drop(index=drop_idx)
y = y.drop(index=drop_idx)

# Verify
print(X.shape, y.shape)  # should both show 780 rows

(780, 53) (780, 3)

In [15]:
# For this variable, since there are only 3 missing values, we can drop the rows with missing values
# Get the indices of the 3 missing patients
drop_idx = X[X['US_Performed'].isna()].index

# Drop from both
X = X.drop(index=drop_idx)
y = y.drop(index=drop_idx)

# Verify
print(X.shape, y.shape)  # should both show 780 rows

(777, 53) (777, 3)

In [16]:
X['Appendix_on_US'].dropna()

0      yes
1       no
2       no
3       no
4      yes
      ...
777    yes
778     no
779     no
780    yes
781    yes
Name: Appendix_on_US, Length: 774, dtype: str

In [17]:
col = 'Appendix_on_US'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.591731
no appendicitis    0.408269
Name: proportion, dtype: float64

In [18]:
col = 'Appendix_on_US'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but 0 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [19]:
nan_summary = pd.DataFrame({
    'dtype': X.dtypes,
    'non_null': X.notna().sum(),
    'nan_count': X.isna().sum(),
    'nan_pct': (X.isna().sum() / len(X) * 100).round(2)
})
nan_summary

                                    dtype  non_null  nan_count  nan_pct
Age                               float64       777          0     0.00
BMI                               float64       777          0     0.00
Sex                                   str       777          0     0.00
Height                            float64       777          0     0.00
Weight                            float64       777          0     0.00
Length_of_Stay                    float64       777          0     0.00
Alvarado_Score                    float64       777          0     0.00
Paedriatic_Appendicitis_Score     float64       777          0     0.00
Appendix_on_US                    float64       777          0     0.00
Appendix_Diameter                 float64       496        281    36.16
Migratory_Pain                        str       770          7     0.90
Lower_Right_Abd_Pain                  str       771          6     0.77
Contralateral_Rebound_Tenderness      str       764         13     1.67
Coughing_Pain                         str       764         13     1.67
Nausea                                str       772          5     0.64
Loss_of_Appetite                      str       770          7     0.90
Body_Temperature                  float64       777          0     0.00
WBC_Count                         float64       777          0     0.00
Neutrophil_Percentage             float64       777          0     0.00
Segmented_Neutrophils             float64        54        723    93.05
Neutrophilia                          str       729         48     6.18
RBC_Count                         float64       777          0     0.00
Hemoglobin                        float64       777          0     0.00
RDW                               float64       777          0     0.00
Thrombocyte_Count                 float64       777          0     0.00
Ketones_in_Urine                      str       581        196    25.23
RBC_in_Urine                          str       575        202    26.00
WBC_in_Urine                          str       582        195    25.10
CRP                               float64       777          0     0.00
Dysuria                               str       750         27     3.47
Stool                                 str       762         15     1.93
Peritonitis                           str       771          6     0.77
Psoas_Sign                            str       743         34     4.38
Ipsilateral_Rebound_Tenderness        str       618        159    20.46
US_Performed                          str       777          0     0.00
Free_Fluids                           str       717         60     7.72
Appendix_Wall_Layers                  str       217        560    72.07
Target_Sign                           str       136        641    82.50
Appendicolith                         str        69        708    91.12
Perfusion                             str        62        715    92.02
Perforation                           str        80        697    89.70
Surrounding_Tissue_Reaction           str       250        527    67.82
Appendicular_Abscess                  str        84        693    89.19
Abscess_Location                      str        13        764    98.33
Pathological_Lymph_Nodes              str       202        575    74.00
Lymph_Nodes_Location                  str       121        656    84.43
Bowel_Wall_Thickening                 str        98        679    87.39
Conglomerate_of_Bowel_Loops           str        43        734    94.47
Ileus                                 str        60        717    92.28
Coprostasis                           str        71        706    90.86
Meteorism                             str       140        637    81.98
Enteritis                             str        66        711    91.51
Gynecological_Findings                str        26        751    96.65
Appendix_on_US_observed             int64       777          0     0.00

In [20]:
X['Migratory_Pain'].dropna()

0       no
1      yes
2       no
3      yes
4       no
      ...
777    yes
778     no
779     no
780    yes
781     no
Name: Migratory_Pain, Length: 770, dtype: str

In [21]:
col = 'Migratory_Pain'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.58961
no appendicitis    0.41039
Name: proportion, dtype: float64

In [22]:
col = 'Migratory_Pain'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but 0 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [23]:
X['Lower_Right_Abd_Pain'].dropna()

0      yes
1      yes
2      yes
3      yes
4      yes
      ...
777    yes
778     no
779    yes
780    yes
781    yes
Name: Lower_Right_Abd_Pain, Length: 771, dtype: str

In [24]:
col = 'Lower_Right_Abd_Pain'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.590143
no appendicitis    0.409857
Name: proportion, dtype: float64

In [25]:
col = 'Lower_Right_Abd_Pain'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [26]:
X['Contralateral_Rebound_Tenderness'].dropna()
col = 'Contralateral_Rebound_Tenderness'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.586387
no appendicitis    0.413613
Name: proportion, dtype: float64

In [27]:
col = 'Contralateral_Rebound_Tenderness'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [28]:
X['Coughing_Pain'].dropna()

0       no
1       no
2       no
3       no
4      yes
      ...
777     no
778     no
779     no
780    yes
781     no
Name: Coughing_Pain, Length: 764, dtype: str

In [29]:
col = 'Coughing_Pain'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.586387
no appendicitis    0.413613
Name: proportion, dtype: float64

In [30]:
col = 'Coughing_Pain'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [31]:
X['Nausea'].dropna()

0       no
1       no
2       no
3      yes
4      yes
      ...
777     no
778     no
779     no
780    yes
781     no
Name: Nausea, Length: 772, dtype: str

In [32]:
col = 'Nausea'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.590674
no appendicitis    0.409326
Name: proportion, dtype: float64

In [33]:
col = 'Nausea'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [34]:
X.shape # (n_rows, n_cols)

(777, 59)

In [35]:
X['Loss_of_Appetite'].dropna()

0      yes
1      yes
2       no
3      yes
4      yes
      ...
777    yes
778    yes
779     no
780     no
781     no
Name: Loss_of_Appetite, Length: 770, dtype: str

In [36]:
col = 'Loss_of_Appetite'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.58961
no appendicitis    0.41039
Name: proportion, dtype: float64

In [37]:
col = 'Loss_of_Appetite'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [38]:
X['Neutrophilia'].dropna()

0       no
1       no
2       no
3       no
4       no
      ...
777    yes
778    yes
779     no
780    yes
781     no
Name: Neutrophilia, Length: 729, dtype: str

In [39]:
col = 'Neutrophilia'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.595745
no appendicitis    0.404255
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.592593
no appendicitis    0.407407
Name: proportion, dtype: float64

In [40]:
X['Neutrophilia'] = X['Neutrophilia'].map({'yes': 1, 'no': 0})
# NaN stays NaN — tree handles it natively

In [41]:
X['Ketones_in_Urine'].dropna().head(20)

0      ++
1      no
2      no
3      no
4      no
5      ++
6      no
8     +++
9      no
10     no
11     no
12    +++
13     no
15     no
16    +++
17     no
18      +
19     no
20      +
21      +
Name: Ketones_in_Urine, dtype: str

In [42]:
col = 'Ketones_in_Urine'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.733333
no appendicitis    0.266667
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.545611
no appendicitis    0.454389
Name: proportion, dtype: float64

In [43]:
col = 'Ketones_in_Urine'

ordinal_map = {
    'no': 0,
    '+': 1,
    '++': 2,
    '+++': 3
}

X[col] = X[col].map(ordinal_map)

In [44]:
# Add indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# Map ordinal, then fill with -1 sentinel
X[col] = X[col].map(ordinal_map).fillna(-1)

In [45]:
X['RBC_in_Urine'].unique()

<StringArray>
['+', 'no', nan, '++', '+++']
Length: 5, dtype: str

In [46]:
col = 'RBC_in_Urine'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.716418
no appendicitis    0.283582
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.549565
no appendicitis    0.450435
Name: proportion, dtype: float64

In [47]:
col = 'RBC_in_Urine'

ordinal_map = {
    'no': 0,
    '+': 1,
    '++': 2,
    '+++': 3
}

X[col] = X[col].map(ordinal_map)

In [48]:
# Add indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# Map ordinal, then fill with -1 sentinel
X[col] = X[col].map(ordinal_map).fillna(-1)

In [49]:
X['WBC_in_Urine'].unique()

<StringArray>
['no', '+', nan, '+++', '++']
Length: 5, dtype: str

In [50]:
col = 'WBC_in_Urine'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.731959
no appendicitis    0.268041
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.546392
no appendicitis    0.453608
Name: proportion, dtype: float64

In [51]:
col = 'WBC_in_Urine'

ordinal_map = {
    'no': 0,
    '+': 1,
    '++': 2,
    '+++': 3
}

X[col] = X[col].map(ordinal_map)

In [52]:
# Add indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# Map ordinal, then fill with -1 sentinel
X[col] = X[col].map(ordinal_map).fillna(-1)

In [53]:
X['Dysuria'].unique()

<StringArray>
['no', 'yes', nan]
Length: 3, dtype: str

In [54]:
col = 'Dysuria'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.961538
no appendicitis    0.038462
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.58
no appendicitis    0.42
Name: proportion, dtype: float64

In [55]:
col = 'Dysuria'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [56]:
X['Stool'].unique()

<StringArray>
['normal', 'constipation', 'diarrhea', nan, 'constipation, diarrhea']
Length: 5, dtype: str

In [57]:
col = 'Stool'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.857143
no appendicitis    0.142857
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.587927
no appendicitis    0.412073
Name: proportion, dtype: float64

In [58]:
# If MNAR — add indicator first, then fill
X[f'{col}_observed'] = X[col].notna().astype(int)
X[col] = X[col].fillna('unknown')  # explicit unknown category

In [59]:
X = pd.get_dummies(X, columns=[col], drop_first=False)

bool_cols = X.select_dtypes(include='bool').columns
X[bool_cols] = X[bool_cols].astype(int)

In [60]:
# Filter out one-hot encoded and indicator columns
mask = ~X.columns.str.contains('_observed|Stool_')  # add your one-hot prefixes here

nan_summary = pd.DataFrame({
    'dtype': X.dtypes[mask],
    'non_null': X.notna().sum()[mask],
    'nan_count': X.isna().sum()[mask],
    'nan_pct': (X.isna().sum() / len(X) * 100).round(2)[mask]
})
nan_summary

                                    dtype  non_null  nan_count  nan_pct
Age                               float64       777          0     0.00
BMI                               float64       777          0     0.00
Sex                                   str       777          0     0.00
Height                            float64       777          0     0.00
Weight                            float64       777          0     0.00
Length_of_Stay                    float64       777          0     0.00
Alvarado_Score                    float64       777          0     0.00
Paedriatic_Appendicitis_Score     float64       777          0     0.00
Appendix_on_US                    float64       777          0     0.00
Appendix_Diameter                 float64       496        281    36.16
Migratory_Pain                    float64       777          0     0.00
Lower_Right_Abd_Pain              float64       777          0     0.00
Contralateral_Rebound_Tenderness  float64       777          0     0.00
Coughing_Pain                     float64       777          0     0.00
Nausea                            float64       777          0     0.00
Loss_of_Appetite                  float64       777          0     0.00
Body_Temperature                  float64       777          0     0.00
WBC_Count                         float64       777          0     0.00
Neutrophil_Percentage             float64       777          0     0.00
Segmented_Neutrophils             float64        54        723    93.05
Neutrophilia                      float64       729         48     6.18
RBC_Count                         float64       777          0     0.00
Hemoglobin                        float64       777          0     0.00
RDW                               float64       777          0     0.00
Thrombocyte_Count                 float64       777          0     0.00
Ketones_in_Urine                  float64       777          0     0.00
RBC_in_Urine                      float64       777          0     0.00
WBC_in_Urine                      float64       777          0     0.00
CRP                               float64       777          0     0.00
Dysuria                           float64       777          0     0.00
Peritonitis                           str       771          6     0.77
Psoas_Sign                            str       743         34     4.38
Ipsilateral_Rebound_Tenderness        str       618        159    20.46
US_Performed                          str       777          0     0.00
Free_Fluids                           str       717         60     7.72
Appendix_Wall_Layers                  str       217        560    72.07
Target_Sign                           str       136        641    82.50
Appendicolith                         str        69        708    91.12
Perfusion                             str        62        715    92.02
Perforation                           str        80        697    89.70
Surrounding_Tissue_Reaction           str       250        527    67.82
Appendicular_Abscess                  str        84        693    89.19
Abscess_Location                      str        13        764    98.33
Pathological_Lymph_Nodes              str       202        575    74.00
Lymph_Nodes_Location                  str       121        656    84.43
Bowel_Wall_Thickening                 str        98        679    87.39
Conglomerate_of_Bowel_Loops           str        43        734    94.47
Ileus                                 str        60        717    92.28
Coprostasis                           str        71        706    90.86
Meteorism                             str       140        637    81.98
Enteritis                             str        66        711    91.51
Gynecological_Findings                str        26        751    96.65

In [61]:
X['Peritonitis'].unique()

<StringArray>
['no', 'local', 'generalized', nan]
Length: 4, dtype: str

In [62]:
col = 'Peritonitis'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis    1.0
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.590143
no appendicitis    0.409857
Name: proportion, dtype: float64

In [63]:
col = 'Peritonitis'

ordinal_map = {
    'no': 0,
    'local': 1,
    'generalized': 2
}

X[col] = X[col].map(ordinal_map)

In [64]:
# Add indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# Map ordinal, then fill with -1 sentinel
X[col] = X[col].map(ordinal_map).fillna(-1)

In [65]:
X['Psoas_Sign'].unique()

<StringArray>
['yes', 'no', nan]
Length: 3, dtype: str

In [66]:
col = 'Psoas_Sign'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.878788
no appendicitis    0.121212
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.580081
no appendicitis    0.419919
Name: proportion, dtype: float64

In [67]:
col = 'Psoas_Sign'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [68]:
X['Ipsilateral_Rebound_Tenderness'].unique()

<StringArray>
['no', 'yes', nan]
Length: 3, dtype: str

In [69]:
col = 'Ipsilateral_Rebound_Tenderness'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.987342
no appendicitis    0.012658
Name: proportion, dtype: float64
Diagnosis
no appendicitis    0.508091
appendicitis       0.491909
Name: proportion, dtype: float64

In [70]:
col = 'Ipsilateral_Rebound_Tenderness'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [71]:
X['Free_Fluids'].unique()

<StringArray>
['no', 'yes', nan]
Length: 3, dtype: str

In [72]:
col = 'Free_Fluids'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.542373
no appendicitis    0.457627
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.596932
no appendicitis    0.403068
Name: proportion, dtype: float64

In [73]:
X['Free_Fluids'] = X['Free_Fluids'].map({'yes': 1, 'no': 0})
# NaN stays NaN — tree handles it natively

In [74]:
X['Appendix_Wall_Layers'].unique()

<StringArray>
['intact', nan, 'raised', 'upset', 'partially raised']
Length: 5, dtype: str

In [75]:
X['Appendix_Wall_Layers'].value_counts(dropna=True)

Appendix_Wall_Layers
intact              132
raised               75
partially raised      9
upset                 1
Name: count, dtype: int64

In [76]:
col = 'Appendix_Wall_Layers'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
no appendicitis    0.506261
appendicitis       0.493739
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.847926
no appendicitis    0.152074
Name: proportion, dtype: float64

In [77]:
col = 'Appendix_Wall_Layers'

# 1. Add MNAR indicator (217/782 observed — likely strong MNAR signal)
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Binary mapping: intact vs any issue
X[col] = X[col].map({
    'intact': 0,
    'raised': 1,
    'partially raised': 1,
    'upset': 1
})

# 3. Sentinel fill for tree-based models
X[col] = X[col].fillna(-1)

In [78]:
X['Target_Sign'].unique()

<StringArray>
[nan, 'yes', 'no']
Length: 3, dtype: str

In [79]:
col = 'Target_Sign'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.554688
no appendicitis    0.445312
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.772059
no appendicitis    0.227941
Name: proportion, dtype: float64

In [80]:
col = 'Target_Sign'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [81]:
X['Appendicolith'].unique()

<StringArray>
['suspected', nan, 'yes', 'no']
Length: 4, dtype: str

In [82]:
col = 'Appendicolith'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.557284
no appendicitis    0.442716
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.956522
no appendicitis    0.043478
Name: proportion, dtype: float64

In [83]:
col = 'Appendicolith'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [84]:
X['Perfusion'].unique()

<StringArray>
[nan, 'hyperperfused', 'hypoperfused', 'no', 'present']
Length: 5, dtype: str

In [85]:
X['Perfusion'].value_counts(dropna=True)

Perfusion
hyperperfused    31
hypoperfused     27
no                3
present           1
Name: count, dtype: int64

In [86]:
# Drop the 1 patient with ambiguous 'present' label
drop_idx = X[X['Perfusion'] == 'present'].index
X = X.drop(index=drop_idx)
y = y.drop(index=drop_idx)

print(X.shape, y.shape)

(776, 75) (776, 3)

In [87]:
col = 'Perfusion'

# Add MNAR indicator
X[f'{col}_observed'] = X[col].notna().astype(int)

# Ordinal-style mapping: distinguishing hypo vs normal vs hyper
X[col] = X[col].map({
    'hypoperfused': 0,
    'no': 1,             # normal
    'hyperperfused': 2
})

# Sentinel fill
X[col] = X[col].fillna(-1)

In [88]:
X['Perforation'].unique()

<StringArray>
['no', nan, 'suspected', 'yes', 'not excluded']
Length: 5, dtype: str

In [89]:
X['Perforation'].value_counts(dropna=True)

Perforation
no              33
yes             29
not excluded    15
suspected        3
Name: count, dtype: int64

In [90]:
col = 'Perforation'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.552518
no appendicitis    0.447482
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.9375
no appendicitis    0.0625
Name: proportion, dtype: float64

In [91]:
col = 'Perforation'

# Add MNAR indicator
X[f'{col}_observed'] = X[col].notna().astype(int)

# Map to 3 categories: no, maybe, yes
X[col] = X[col].map({
    'no': 0,
    'not excluded': 1,
    'suspected': 1,
    'yes': 2
})

# Sentinel fill
X[col] = X[col].fillna(-1)

In [92]:
X['Surrounding_Tissue_Reaction'].unique()

<StringArray>
['yes', nan, 'no']
Length: 3, dtype: str

In [93]:
col = 'Surrounding_Tissue_Reaction'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
no appendicitis    0.547529
appendicitis       0.452471
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.88755
no appendicitis    0.11245
Name: proportion, dtype: float64

In [94]:
col = 'Surrounding_Tissue_Reaction'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [95]:
X['Appendicular_Abscess'].unique()

<StringArray>
['no', nan, 'suspected', 'yes']
Length: 4, dtype: str

In [ ]:
X['Appendicular_Abscess'].value_counts(dropna=True)

Appendicular_Abscess
no           65
yes          18
suspected     1
Name: count, dtype: int64

In [97]:
col = 'Appendicular_Abscess'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.555716
no appendicitis    0.444284
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.892857
no appendicitis    0.107143
Name: proportion, dtype: float64

In [98]:
# Drop the 1 patient with 'suspected'
drop_idx = X[X['Appendicular_Abscess'] == 'suspected'].index
X = X.drop(index=drop_idx)
y = y.drop(index=drop_idx)

print(X.shape, y.shape)

(775, 78) (775, 3)

In [99]:
col = 'Appendicular_Abscess'

# Add MNAR indicator
X[f'{col}_observed'] = X[col].notna().astype(int)

# Binary mapping
X[col] = X[col].map({
    'no': 0,
    'yes': 1
})

# Sentinel fill
X[col] = X[col].fillna(-1)

In [100]:
X['Abscess_Location'].unique()

<StringArray>
[                     nan,                'Douglas',           'retrovesikal',
     'rechter Unterbauch',        'perityphlitisch', 'an den M. psoas rechts',
    'rechter Mittelbauch',         're Mittelbauch']
Length: 8, dtype: str

In [101]:
X = X.drop(columns=['Abscess_Location'])

In [102]:
X['Pathological_Lymph_Nodes'].unique()

<StringArray>
['yes', nan, 'no']
Length: 3, dtype: str

In [103]:
col = 'Pathological_Lymph_Nodes'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.608392
no appendicitis    0.391608
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.544554
no appendicitis    0.455446
Name: proportion, dtype: float64

In [104]:
X['Pathological_Lymph_Nodes'] = X['Pathological_Lymph_Nodes'].map({'yes': 1, 'no': 0})
# NaN stays NaN — tree handles it natively

In [ ]:
X['Lymph_Nodes_Location'].unique()

<StringArray>
[                          'reUB',                              nan,
                          're UB',                      'Ileozökal',
                             'UB',                         're UB ',
                  'periumbilikal',                     'ileocoekal',
             'mesenterial, re UB',                    'mesenterial',
           're UB, periumbilikal',                        're UB  ',
              're UB, ileocoecal',                     'ileocoecal',
                   're UB, re MB',                             'MB',
                          're MB',                       'inguinal',
              'periappendikulär ',    'Mesenterial, links inguinal',
             'rechter Unterbauch',                      'ileocöcal',
        'multiple Lokalisationen',          'lokal um die Appendix',
 'rechter Unter- und Mittelbauch',                  'Ovarialzysten']
Length: 26, dtype: str

In [106]:
X = X.drop(columns=['Lymph_Nodes_Location'])

In [107]:
X['Bowel_Wall_Thickening'].unique()

<StringArray>
[nan, 'no', 'yes']
Length: 3, dtype: str

In [108]:
col = 'Bowel_Wall_Thickening'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.576923
no appendicitis    0.423077
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.693878
no appendicitis    0.306122
Name: proportion, dtype: float64

In [109]:
col = 'Bowel_Wall_Thickening'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [110]:
X['Conglomerate_of_Bowel_Loops'].unique()

<StringArray>
[nan, 'no', 'yes']
Length: 3, dtype: str

In [111]:
col = 'Conglomerate_of_Bowel_Loops'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.575923
no appendicitis    0.424077
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.860465
no appendicitis    0.139535
Name: proportion, dtype: float64

In [112]:
col = 'Conglomerate_of_Bowel_Loops'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [113]:
X['Ileus'].unique()

<StringArray>
[nan, 'no', 'yes']
Length: 3, dtype: str

In [114]:
col = 'Ileus'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.565826
no appendicitis    0.434174
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.9
no appendicitis    0.1
Name: proportion, dtype: float64

In [115]:
col = 'Ileus'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [116]:
X['Coprostasis'].unique()

<StringArray>
[nan, 'yes', 'no']
Length: 3, dtype: str

In [117]:
col = 'Coprostasis'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.583215
no appendicitis    0.416785
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.676056
no appendicitis    0.323944
Name: proportion, dtype: float64

In [118]:
col = 'Coprostasis'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [119]:
X['Meteorism'].unique()

<StringArray>
[nan, 'yes', 'no']
Length: 3, dtype: str

In [120]:
col = 'Meteorism'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.611987
no appendicitis    0.388013
Name: proportion, dtype: float64
Diagnosis
no appendicitis    0.5
appendicitis       0.5
Name: proportion, dtype: float64

In [121]:
col = 'Meteorism'

# 1. Add the indicator first
X[f'{col}_observed'] = X[col].notna().astype(int)

# 2. Map yes/no to 1/0
X[col] = X[col].map({'yes': 1, 'no': 0})

# 3. Fill NaN with sentinel — for tree based models you could leave it
# but -1 is a safe neutral fill that won't create spurious splits
X[col] = X[col].fillna(-1)

In [122]:
X['Enteritis'].unique()

<StringArray>
[nan, 'yes', 'no']
Length: 3, dtype: str

In [123]:
col = 'Enteritis'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.605932
no appendicitis    0.394068
Name: proportion, dtype: float64
Diagnosis
no appendicitis    0.560606
appendicitis       0.439394
Name: proportion, dtype: float64

In [124]:
X['Enteritis'] = X['Enteritis'].map({'yes': 1, 'no': 0})
# NaN stays NaN — tree handles it natively

In [125]:
X['Gynecological_Findings'].unique()

<StringArray>
[                                                                                                                                                                                          nan,
                                                                                                                                                                                'Ovarialzyste',
                                                                                                                                                                                'Zyste Uterus',
                                                                                                                                                                               'Ovarialzyste ',
 'In beiden Ovarien Zysten darstellbar, links Ovar mit regelrechter Perfusion, rechts etwas vergrößert, keine eindeutige Perfusion nachweisbar. Retrovesikal freie Flüssigkeit mit Binnenecho',
                                                                                                                                                     'Ausschluss pathologischer Ovarialbefund',
                                                                                                                                                                     'kleine Ovarzyste rechts',
                                                                                                                                 'kein Anhalt für eine gynäkologische Ursache der Beschwerden',
                                                                                                                                                                        'V. a. Ovarialtorsion',
                                                                                                                                                     'Ausschluss gyn. Ursache der Beschwerden',
                                                                                                                                                                                          'ja',
                                                                                                                                                                                       'keine',
                                                                                                                                                                               'Ovarialzysten',
                                                                                                                                                                            'Ovarialzyste re.',
                                                                                                                                                                                 'unauffällig']
Length: 15, dtype: str

In [126]:
X = X.drop(columns=['Gynecological_Findings'])

In [129]:
nan_summary = pd.DataFrame({
    'dtype': X.dtypes,
    'non_null': X.notna().sum(),
    'nan_count': X.isna().sum(),
    'nan_pct': (X.isna().sum() / len(X) * 100).round(2)
})

In [130]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(nan_summary)

,dtype,non_null,nan_count,nan_pct
Age,float64,775,0,0.00
BMI,float64,775,0,0.00
Sex,str,775,0,0.00
Height,float64,775,0,0.00
Weight,float64,775,0,0.00
Length_of_Stay,float64,775,0,0.00
Alvarado_Score,float64,775,0,0.00
Paedriatic_Appendicitis_Score,float64,775,0,0.00
Appendix_on_US,float64,775,0,0.00
Appendix_Diameter,float64,495,280,36.13
Migratory_Pain,float64,775,0,0.00
Lower_Right_Abd_Pain,float64,775,0,0.00
Contralateral_Rebound_Tenderness,float64,775,0,0.00
Coughing_Pain,float64,775,0,0.00
Nausea,float64,775,0,0.00
Loss_of_Appetite,float64,775,0,0.00
Body_Temperature,float64,775,0,0.00
WBC_Count,float64,775,0,0.00
Neutrophil_Percentage,float64,775,0,0.00
Segmented_Neutrophils,float64,54,721,93.03
Neutrophilia,float64,727,48,6.19
RBC_Count,float64,775,0,0.00
Hemoglobin,float64,775,0,0.00
RDW,float64,775,0,0.00
Thrombocyte_Count,float64,775,0,0.00
Ketones_in_Urine,float64,775,0,0.00
RBC_in_Urine,float64,775,0,0.00
WBC_in_Urine,float64,775,0,0.00
CRP,float64,775,0,0.00
Dysuria,float64,775,0,0.00
Peritonitis,float64,775,0,0.00
Psoas_Sign,float64,775,0,0.00
Ipsilateral_Rebound_Tenderness,float64,775,0,0.00
US_Performed,str,775,0,0.00
Free_Fluids,float64,715,60,7.74
Appendix_Wall_Layers,float64,775,0,0.00
Target_Sign,float64,775,0,0.00
Appendicolith,float64,775,0,0.00
Perfusion,float64,775,0,0.00
Perforation,float64,775,0,0.00
Surrounding_Tissue_Reaction,float64,775,0,0.00
Appendicular_Abscess,float64,775,0,0.00
Pathological_Lymph_Nodes,float64,202,573,73.94
Bowel_Wall_Thickening,float64,775,0,0.00
Conglomerate_of_Bowel_Loops,float64,775,0,0.00
Ileus,float64,775,0,0.00
Coprostasis,float64,775,0,0.00
Meteorism,float64,775,0,0.00
Enteritis,float64,66,709,91.48
Appendix_on_US_observed,int64,775,0,0.00
Migratory_Pain_observed,int64,775,0,0.00
Lower_Right_Abd_Pain_observed,int64,775,0,0.00
Contralateral_Rebound_Tenderness_observed,int64,775,0,0.00
Coughing_Pain_observed,int64,775,0,0.00
Nausea_observed,int64,775,0,0.00
Loss_of_Appetite_observed,int64,775,0,0.00
Ketones_in_Urine_observed,int64,775,0,0.00
RBC_in_Urine_observed,int64,775,0,0.00
WBC_in_Urine_observed,int64,775,0,0.00
Dysuria_observed,int64,775,0,0.00
Stool_observed,int64,775,0,0.00
Stool_constipation,int64,775,0,0.00
"Stool_constipation, diarrhea",int64,775,0,0.00
Stool_diarrhea,int64,775,0,0.00
Stool_normal,int64,775,0,0.00
Stool_unknown,int64,775,0,0.00
Peritonitis_observed,int64,775,0,0.00
Psoas_Sign_observed,int64,775,0,0.00
Ipsilateral_Rebound_Tenderness_observed,int64,775,0,0.00
Appendix_Wall_Layers_observed,int64,775,0,0.00
Target_Sign_observed,int64,775,0,0.00
Appendicolith_observed,int64,775,0,0.00
Perfusion_observed,int64,775,0,0.00
Perforation_observed,int64,775,0,0.00
Surrounding_Tissue_Reaction_observed,int64,775,0,0.00
Appendicular_Abscess_observed,int64,775,0,0.00
Bowel_Wall_Thickening_observed,int64,775,0,0.00
Conglomerate_of_Bowel_Loops_observed,int64,775,0,0.00
Ileus_observed,int64,775,0,0.00
Coprostasis_observed,int64,775,0,0.00
Meteorism_observed,int64,775,0,0.00

In [132]:
X['Appendix_Diameter'].head(20)

0     7.1
1     NaN
2     NaN
3     NaN
4     7.0
5     NaN
6     NaN
7     NaN
8     3.7
9     8.0
10    9.0
11    NaN
12    NaN
13    NaN
14    9.0
15    9.0
16    8.5
17    9.3
18    9.0
19    5.0
Name: Appendix_Diameter, dtype: float64

In [133]:
col = 'Appendix_Diameter'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
no appendicitis    0.677419
appendicitis       0.322581
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.743434
no appendicitis    0.256566
Name: proportion, dtype: float64

In [134]:
# Add MNAR indicator
X[f'{col}_observed'] = X[col].notna().astype(int)

# Median imputation using only the observed values
X[col] = X[col].fillna(X[col].median())

In [136]:
X['Segmented_Neutrophils'].unique()

array([ nan, 61. , 60. , 88. , 54. , 39. , 46. , 64. , 32. , 73. , 63. ,
       62. , 68. , 41. , 87. , 59. , 51. , 79. , 67. , 74. , 38. , 66. ,
       52. , 78. , 76. , 82.2, 91. , 56. , 84. , 82. , 69. , 81. , 86. ,
       65. , 58. , 80. , 83. , 72. , 53. , 33. ])

In [137]:
col = 'Segmented_Neutrophils'

# Is missingness correlated with the diagnosis?
missing_mask = X[col].isna()
print(y['Diagnosis'][missing_mask].value_counts(normalize=True))   # among missing
print(y['Diagnosis'][~missing_mask].value_counts(normalize=True))  # among observed

Diagnosis
appendicitis       0.591667
no appendicitis    0.408333
Name: proportion, dtype: float64
Diagnosis
appendicitis       0.592593
no appendicitis    0.407407
Name: proportion, dtype: float64

In [138]:
X[col] = X[col].fillna(X[col].median())

In [141]:
X['Sex'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [142]:
col = 'Sex'

binary_map = {
    'male': 0,
    'female': 1
}

X[col] = X[col].map(binary_map)

In [143]:
X['US_Performed'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [144]:
col = 'US_Performed'
X[col] = X[col].map({'yes': 1, 'no': 0})

In [145]:
nan_summary = pd.DataFrame({
    'dtype': X.dtypes,
    'non_null': X.notna().sum(),
    'nan_count': X.isna().sum(),
    'nan_pct': (X.isna().sum() / len(X) * 100).round(2)
})

In [146]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(nan_summary)

,dtype,non_null,nan_count,nan_pct
Age,float64,775,0,0.00
BMI,float64,775,0,0.00
Sex,int64,775,0,0.00
Height,float64,775,0,0.00
Weight,float64,775,0,0.00
Length_of_Stay,float64,775,0,0.00
Alvarado_Score,float64,775,0,0.00
Paedriatic_Appendicitis_Score,float64,775,0,0.00
Appendix_on_US,float64,775,0,0.00
Appendix_Diameter,float64,775,0,0.00
Migratory_Pain,float64,775,0,0.00
Lower_Right_Abd_Pain,float64,775,0,0.00
Contralateral_Rebound_Tenderness,float64,775,0,0.00
Coughing_Pain,float64,775,0,0.00
Nausea,float64,775,0,0.00
Loss_of_Appetite,float64,775,0,0.00
Body_Temperature,float64,775,0,0.00
WBC_Count,float64,775,0,0.00
Neutrophil_Percentage,float64,775,0,0.00
Segmented_Neutrophils,float64,775,0,0.00
Neutrophilia,float64,727,48,6.19
RBC_Count,float64,775,0,0.00
Hemoglobin,float64,775,0,0.00
RDW,float64,775,0,0.00
Thrombocyte_Count,float64,775,0,0.00
Ketones_in_Urine,float64,775,0,0.00
RBC_in_Urine,float64,775,0,0.00
WBC_in_Urine,float64,775,0,0.00
CRP,float64,775,0,0.00
Dysuria,float64,775,0,0.00
Peritonitis,float64,775,0,0.00
Psoas_Sign,float64,775,0,0.00
Ipsilateral_Rebound_Tenderness,float64,775,0,0.00
US_Performed,int64,775,0,0.00
Free_Fluids,float64,715,60,7.74
Appendix_Wall_Layers,float64,775,0,0.00
Target_Sign,float64,775,0,0.00
Appendicolith,float64,775,0,0.00
Perfusion,float64,775,0,0.00
Perforation,float64,775,0,0.00
Surrounding_Tissue_Reaction,float64,775,0,0.00
Appendicular_Abscess,float64,775,0,0.00
Pathological_Lymph_Nodes,float64,202,573,73.94
Bowel_Wall_Thickening,float64,775,0,0.00
Conglomerate_of_Bowel_Loops,float64,775,0,0.00
Ileus,float64,775,0,0.00
Coprostasis,float64,775,0,0.00
Meteorism,float64,775,0,0.00
Enteritis,float64,66,709,91.48
Appendix_on_US_observed,int64,775,0,0.00
Migratory_Pain_observed,int64,775,0,0.00
Lower_Right_Abd_Pain_observed,int64,775,0,0.00
Contralateral_Rebound_Tenderness_observed,int64,775,0,0.00
Coughing_Pain_observed,int64,775,0,0.00
Nausea_observed,int64,775,0,0.00
Loss_of_Appetite_observed,int64,775,0,0.00
Ketones_in_Urine_observed,int64,775,0,0.00
RBC_in_Urine_observed,int64,775,0,0.00
WBC_in_Urine_observed,int64,775,0,0.00
Dysuria_observed,int64,775,0,0.00
Stool_observed,int64,775,0,0.00
Stool_constipation,int64,775,0,0.00
"Stool_constipation, diarrhea",int64,775,0,0.00
Stool_diarrhea,int64,775,0,0.00
Stool_normal,int64,775,0,0.00
Stool_unknown,int64,775,0,0.00
Peritonitis_observed,int64,775,0,0.00
Psoas_Sign_observed,int64,775,0,0.00
Ipsilateral_Rebound_Tenderness_observed,int64,775,0,0.00
Appendix_Wall_Layers_observed,int64,775,0,0.00
Target_Sign_observed,int64,775,0,0.00
Appendicolith_observed,int64,775,0,0.00
Perfusion_observed,int64,775,0,0.00
Perforation_observed,int64,775,0,0.00
Surrounding_Tissue_Reaction_observed,int64,775,0,0.00
Appendicular_Abscess_observed,int64,775,0,0.00
Bowel_Wall_Thickening_observed,int64,775,0,0.00
Conglomerate_of_Bowel_Loops_observed,int64,775,0,0.00
Ileus_observed,int64,775,0,0.00
Coprostasis_observed,int64,775,0,0.00
Meteorism_observed,int64,775,0,0.00
Appendix_Diameter_observed,int64,775,0,0.00